version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-db/
    image: haleemo/vprodb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vprofiledb
    volumes:
      - vprodbdata:/var/lib/mysql
    container_name: vprodb

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-app/
    image: haleemo/vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    container_name: vproapp


volumes:
  vproappdata: {}
  vprodbdata: {}
